// implementations/vue/src/components/TransferForm.vue
<!--
  TransferForm - Multi-Step Vue Component
  
  PROVIDE/INJECT:
  - Vue's dependency injection system
  - Parent provides data, any descendant can inject it
  - WHY? Avoids "prop drilling" (passing props through many levels)
  - Similar to React's Context API
  - BUT: Not reactive by default (must use reactive/ref)
  
  MULTI-STEP FORMS in Vue:
  - v-if/v-else-if to show current step
  - Keep form state in reactive() for persistence
  - Each step can be a separate component
  - Use provide/inject to share form state
-->
<script setup>
import { ref, reactive, computed, provide } from 'vue';
import { useAccountStore } from '../store/accounts';
import { api } from '../services/api';
import { formatCurrency } from '../utils/helpers';

const accountStore = useAccountStore();
const step = ref(1);
const isSubmitting = ref(false);
const result = ref(null);

// Form data persists across steps
const formData = reactive({
  fromAccountId: '',
  toAccountId: '',
  amount: 0,
  description: '',
});

// Validation errors per step
const errors = reactive({
  fromAccountId: '',
  toAccountId: '',
  amount: '',
  description: '',
});

// WHY provide form state to child components?
// If steps were separate components, they could inject this
provide('transferForm', { formData, errors });

// Computed validation for step 1
const isStep1Valid = computed(() => {
  return formData.fromAccountId && formData.toAccountId;
});

// Computed validation for step 2
const isStep2Valid = computed(() => {
  return formData.amount > 0 && formData.description.length > 0;
});

function validateStep1() {
  errors.fromAccountId = formData.fromAccountId ? '' : 'Select a source account';
  errors.toAccountId = formData.toAccountId ? '' : 'Select a destination account';
  return !errors.fromAccountId && !errors.toAccountId;
}

function validateStep2() {
  errors.amount = formData.amount > 0 ? '' : 'Amount must be positive';
  errors.description = formData.description ? '' : 'Description is required';
  return !errors.amount && !errors.description;
}

function nextStep() {
  if (step.value === 1 && validateStep1()) {
    step.value = 2;
  } else if (step.value === 2 && validateStep2()) {
    step.value = 3;
  }
}

function prevStep() {
  step.value--;
}

async function confirmTransfer() {
  isSubmitting.value = true;
  try {
    const response = await api.post('/transfers', {
      fromAccountId: formData.fromAccountId,
      toAccountId: formData.toAccountId,
      amount: formData.amount,
      description: formData.description,
    });
    result.value = { success: true, transactionId: response.data.id };
  } catch (err) {
    result.value = {
      success: false,
      error: err.response?.data?.message || 'Transfer failed',
    };
  } finally {
    isSubmitting.value = false;
  }
}

function resetForm() {
  step.value = 1;
  formData.fromAccountId = '';
  formData.toAccountId = '';
  formData.amount = 0;
  formData.description = '';
  result.value = null;
}

// Account helper
function getAccountName(id) {
  const account = accountStore.accounts.find((a) => a.id === id);
  return account ? account.name : 'Unknown';
}
</script>

<template>
  <div class="transfer-form">
    <h1>Transfer Money</h1>

    <!-- Step indicator -->
    <div class="step-indicator">
      <div
        v-for="s in 3"
        :key="s"
        class="step"
        :class="{ active: step === s, completed: step > s }"
      >
        <span class="step-number">{{ s }}</span>
        <span class="step-label">
          {{ s === 1 ? 'Accounts' : s === 2 ? 'Details' : 'Confirm' }}
        </span>
      </div>
    </div>

    <!-- Result screen -->
    <div v-if="result" class="transfer-result">
      <h2>{{ result.success ? 'Transfer Complete!' : 'Transfer Failed' }}</h2>
      <p v-if="result.success">Transaction ID: {{ result.transactionId }}</p>
      <p v-else class="error">{{ result.error }}</p>
      <button @click="resetForm">New Transfer</button>
    </div>

    <!-- Step 1: Select Accounts -->
    <form v-else-if="step === 1" @submit.prevent="nextStep">
      <h2>Select Accounts</h2>

      <div class="form-group">
        <label>From Account</label>
        <select v-model="formData.fromAccountId">
          <option value="">Select account</option>
          <option
            v-for="account in accountStore.accounts"
            :key="account.id"
            :value="account.id"
          >
            {{ account.name }} ({{ formatCurrency(account.balance) }})
          </option>
        </select>
        <span v-if="errors.fromAccountId" class="error-message">
          {{ errors.fromAccountId }}
        </span>
      </div>

      <div class="form-group">
        <label>To Account</label>
        <select v-model="formData.toAccountId">
          <option value="">Select account</option>
          <option
            v-for="account in accountStore.accounts"
            :key="account.id"
            :value="account.id"
          >
            {{ account.name }}
          </option>
        </select>
        <span v-if="errors.toAccountId" class="error-message">
          {{ errors.toAccountId }}
        </span>
      </div>

      <button type="submit">Next</button>
    </form>

    <!-- Step 2: Enter Amount -->
    <form v-else-if="step === 2" @submit.prevent="nextStep">
      <h2>Transfer Details</h2>

      <div class="form-group">
        <label>Amount</label>
        <!--
          v-model.number modifier converts input to number
          Alternative: v-model="formData.amount" with type="number"
        -->
        <input
          v-model.number="formData.amount"
          type="number"
          step="0.01"
          min="0.01"
        />
        <span v-if="errors.amount" class="error-message">
          {{ errors.amount }}
        </span>
      </div>

      <div class="form-group">
        <label>Description</label>
        <textarea v-model="formData.description" rows="3"></textarea>
        <span v-if="errors.description" class="error-message">
          {{ errors.description }}
        </span>
      </div>

      <div class="step-actions">
        <button type="button" @click="prevStep">Back</button>
        <button type="submit">Review</button>
      </div>
    </form>

    <!-- Step 3: Confirm -->
    <div v-else-if="step === 3" class="transfer-confirm">
      <h2>Confirm Transfer</h2>
      <div class="confirm-details">
        <p><strong>From:</strong> {{ getAccountName(formData.fromAccountId) }}</p>
        <p><strong>To:</strong> {{ getAccountName(formData.toAccountId) }}</p>
        <p><strong>Amount:</strong> {{ formatCurrency(formData.amount) }}</p>
        <p><strong>Description:</strong> {{ formData.description }}</p>
      </div>
      <div class="step-actions">
        <button @click="prevStep">Back</button>
        <button :disabled="isSubmitting" @click="confirmTransfer">
          {{ isSubmitting ? 'Processing...' : 'Confirm Transfer' }}
        </button>
      </div>
    </div>
  </div>
</template>

// implementations/react/src/components/TransferForm.jsx
/**
 * TransferForm - Multi-Step Form Component
 * 
 * MULTI-STEP FORMS in React:
 * - Break complex forms into manageable steps
 * - Each step validates before proceeding
 * - Preserve form state across steps
 * - Common patterns: wizard, stepper, multi-page form
 * 
 * STEP MANAGEMENT approaches:
 * 1. useState with step counter (this implementation)
 * 2. useReducer for complex state machines
 * 3. Third-party: react-step-wizard, formik multi-step
 * 4. URL-based: Each step has its own route
 * 
 * FORM STATE across steps:
 * - LIFT STATE UP: Parent holds all form data
 * - Each step only reads/writes its portion
 * - Final step submits everything
 * - WHY? Single source of truth, easy validation
 */
import React, { useState, useCallback } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useSelector } from 'react-redux';
import { api } from '../services/api';
import { formatCurrency } from '../utils/helpers';

// Step 1: Select accounts
const step1Schema = z.object({
  fromAccountId: z.string().min(1, 'Please select a source account'),
  toAccountId: z.string().min(1, 'Please select a destination account'),
});

// Step 2: Enter amount and details
const step2Schema = z.object({
  amount: z
    .number()
    .positive('Amount must be positive')
    .min(0.01, 'Minimum transfer amount is $0.01'),
  description: z
    .string()
    .min(1, 'Description is required')
    .max(200, 'Description must be 200 characters or less'),
});

// Step 3: Confirm (no additional validation needed)

export default function TransferForm() {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [result, setResult] = useState(null);
  
  const { data: accounts } = useSelector((state) => state.accounts);

  // WHY separate form instances per step?
  // Each step has its own validation schema
  // Cleaner than one massive schema for everything
  const step1Form = useForm({
    resolver: zodResolver(step1Schema),
  });

  const step2Form = useForm({
    resolver: zodResolver(step2Schema),
  });

  // WHY useCallback for step handlers?
  // Stable references prevent unnecessary re-renders
  const handleStep1Submit = useCallback((data) => {
    setFormData((prev) => ({ ...prev, ...data }));
    setStep(2);
  }, []);

  const handleStep2Submit = useCallback((data) => {
    setFormData((prev) => ({ ...prev, ...data }));
    setStep(3);
  }, []);

  const handleConfirm = useCallback(async () => {
    setIsSubmitting(true);
    try {
      const response = await api.post('/transfers', {
        fromAccountId: formData.fromAccountId,
        toAccountId: formData.toAccountId,
        amount: formData.amount,
        description: formData.description,
      });
      setResult({ success: true, transactionId: response.data.id });
    } catch (err) {
      setResult({ success: false, error: err.response?.data?.message });
    } finally {
      setIsSubmitting(false);
    }
  }, [formData]);

  const handleBack = useCallback(() => {
    setStep((prev) => prev - 1);
  }, []);

  // WHY render function instead of ternary?
  // More readable for multi-step forms
  // Each step's logic is clearly separated
  const renderStep = () => {
    switch (step) {
      case 1:
        return (
          <form onSubmit={step1Form.handleSubmit(handleStep1Submit)}>
            <h2>Select Accounts</h2>
            
            <div className="form-group">
              <label>From Account</label>
              <select {...step1Form.register('fromAccountId')}>
                <option value="">Select account</option>
                {accounts?.map((account) => (
                  <option key={account.id} value={account.id}>
                    {account.name} ({formatCurrency(account.balance)})
                  </option>
                ))}
              </select>
              {step1Form.formState.errors.fromAccountId && (
                <span className="error">
                  {step1Form.formState.errors.fromAccountId.message}
                </span>
              )}
            </div>

            <div className="form-group">
              <label>To Account</label>
              <select {...step1Form.register('toAccountId')}>
                <option value="">Select account</option>
                {accounts?.map((account) => (
                  <option key={account.id} value={account.id}>
                    {account.name}
                  </option>
                ))}
              </select>
              {step1Form.formState.errors.toAccountId && (
                <span className="error">
                  {step1Form.formState.errors.toAccountId.message}
                </span>
              )}
            </div>

            <button type="submit">Next</button>
          </form>
        );

      case 2:
        return (
          <form onSubmit={step2Form.handleSubmit(handleStep2Submit)}>
            <h2>Transfer Details</h2>
            
            <div className="form-group">
              <label>Amount</label>
              <input
                type="number"
                step="0.01"
                {...step2Form.register('amount', { valueAsNumber: true })}
              />
              {step2Form.formState.errors.amount && (
                <span className="error">
                  {step2Form.formState.errors.amount.message}
                </span>
              )}
            </div>

            <div className="form-group">
              <label>Description</label>
              <textarea
                {...step2Form.register('description')}
                rows={3}
              />
              {step2Form.formState.errors.description && (
                <span className="error">
                  {step2Form.formState.errors.description.message}
                </span>
              )}
            </div>

            <div className="step-actions">
              <button type="button" onClick={handleBack}>
                Back
              </button>
              <button type="submit">Review</button>
            </div>
          </form>
        );

      case 3:
        if (result) {
          return (
            <div className="transfer-result">
              <h2>{result.success ? 'Transfer Complete!' : 'Transfer Failed'}</h2>
              {result.success ? (
                <p>Transaction ID: {result.transactionId}</p>
              ) : (
                <p className="error">{result.error}</p>
              )}
              <button onClick={() => { setStep(1); setFormData({}); setResult(null); }}>
                New Transfer
              </button>
            </div>
          );
        }

        return (
          <div className="transfer-confirm">
            <h2>Confirm Transfer</h2>
            <div className="confirm-details">
              <p><strong>From:</strong> {accounts?.find((a) => a.id === formData.fromAccountId)?.name}</p>
              <p><strong>To:</strong> {accounts?.find((a) => a.id === formData.toAccountId)?.name}</p>
              <p><strong>Amount:</strong> {formatCurrency(formData.amount)}</p>
              <p><strong>Description:</strong> {formData.description}</p>
            </div>
            <div className="step-actions">
              <button onClick={handleBack}>Back</button>
              <button onClick={handleConfirm} disabled={isSubmitting}>
                {isSubmitting ? 'Processing...' : 'Confirm Transfer'}
              </button>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="transfer-form">
      <h1>Transfer Money</h1>
      
      {/* Step indicator */}
      <div className="step-indicator">
        {[1, 2, 3].map((s) => (
          <div
            key={s}
            className={`step ${step === s ? 'active' : ''} ${step > s ? 'completed' : ''}`}
          >
            <span className="step-number">{s}</span>
            <span className="step-label">
              {s === 1 ? 'Accounts' : s === 2 ? 'Details' : 'Confirm'}
            </span>
          </div>
        ))}
      </div>

      {renderStep()}
    </div>
  );
}
